/* Prefix Galaxy Mission — 45 verified questions */
window.PREFIX_QUESTIONS = [
  /* =======================================================
     Planet 1: Meaning Moon — Questions 1–9
     ======================================================= */
  {
    id: 1,
    planet: 1,
    type: 'multiple-choice',
    question: 'What does the prefix “un-” usually mean?',
    options: ['not', 'again', 'before', 'between'],
    correctAnswer: 'not',
    explanation: 'un- มักหมายถึง “ไม่” หรือทำให้คำมีความหมายตรงข้าม เช่น unhappy = ไม่มีความสุข',
    prefix: 'un-',
    prefixMeaning: 'not / ไม่',
    baseWord: 'happy',
    baseMeaning: 'มีความสุข',
    newWord: 'unhappy',
    meaning: 'ไม่มีความสุข',
    sentenceTranslation: 'unhappy หมายถึง ไม่มีความสุข',
    difficulty: 'easy'
  },
  {
    id: 2,
    planet: 1,
    type: 'multiple-choice',
    question: 'Which prefix means “again”?',
    options: ['re-', 'pre-', 'mis-', 'sub-'],
    correctAnswer: 're-',
    explanation: 're- หมายถึง “อีกครั้ง” เช่น rebuild = สร้างใหม่อีกครั้ง',
    prefix: 're-',
    prefixMeaning: 'again / อีกครั้ง',
    baseWord: 'build',
    baseMeaning: 'สร้าง',
    newWord: 'rebuild',
    meaning: 'สร้างใหม่',
    sentenceTranslation: 'rebuild หมายถึง สร้างขึ้นใหม่อีกครั้ง',
    difficulty: 'easy'
  },
  {
    id: 3,
    planet: 1,
    type: 'multiple-choice',
    question: 'The prefix “pre-” expresses which idea?',
    options: ['before', 'after', 'wrongly', 'too much'],
    correctAnswer: 'before',
    explanation: 'pre- หมายถึง “ก่อน” เช่น pretest คือแบบทดสอบก่อนเรียน',
    prefix: 'pre-',
    prefixMeaning: 'before / ก่อน',
    baseWord: 'test',
    baseMeaning: 'การทดสอบ',
    newWord: 'pretest',
    meaning: 'แบบทดสอบก่อนเรียน',
    sentenceTranslation: 'pretest คือการทดสอบที่ทำก่อนเริ่มเรียน',
    difficulty: 'easy'
  },
  {
    id: 4,
    planet: 1,
    type: 'multiple-choice',
    question: 'Which prefix means “against”?',
    options: ['anti-', 'co-', 'post-', 'semi-'],
    correctAnswer: 'anti-',
    explanation: 'anti- หมายถึง “ต่อต้าน” เช่น antiwar = ต่อต้านสงคราม',
    prefix: 'anti-',
    prefixMeaning: 'against / ต่อต้าน',
    baseWord: 'war',
    baseMeaning: 'สงคราม',
    newWord: 'antiwar',
    meaning: 'ต่อต้านสงคราม',
    sentenceTranslation: 'antiwar ใช้อธิบายสิ่งที่ต่อต้านสงคราม',
    difficulty: 'easy'
  },
  {
    id: 5,
    planet: 1,
    type: 'multiple-choice',
    question: 'Which prefix represents the number three?',
    options: ['tri-', 'bi-', 'mono-', 'multi-'],
    correctAnswer: 'tri-',
    explanation: 'tri- หมายถึง “สาม” เช่น triangle มีสามมุม',
    prefix: 'tri-',
    prefixMeaning: 'three / สาม',
    baseWord: 'angle',
    baseMeaning: 'มุม',
    newWord: 'triangle',
    meaning: 'รูปสามเหลี่ยม',
    sentenceTranslation: 'triangle คือรูปที่มีสามมุม',
    difficulty: 'easy'
  },
  {
    id: 6,
    planet: 1,
    type: 'multiple-choice',
    question: 'In the word “underpaid,” what does “under-” mean?',
    options: ['too little', 'too much', 'together', 'after'],
    correctAnswer: 'too little',
    explanation: 'under- ใน underpaid หมายถึง “น้อยเกินไป” จึงแปลว่าได้รับค่าจ้างต่ำเกินไป',
    prefix: 'under-',
    prefixMeaning: 'below or too little / ใต้หรือน้อยเกินไป',
    baseWord: 'paid',
    baseMeaning: 'ได้รับค่าจ้าง',
    newWord: 'underpaid',
    meaning: 'ได้รับค่าจ้างต่ำเกินไป',
    sentenceTranslation: 'underpaid หมายถึง ได้รับค่าจ้างน้อยกว่าที่เหมาะสม',
    difficulty: 'medium'
  },
  {
    id: 7,
    planet: 1,
    type: 'multiple-choice',
    question: 'Which prefix best completes the idea “between nations”?',
    options: ['inter-', 'sub-', 'super-', 'mono-'],
    correctAnswer: 'inter-',
    explanation: 'inter- หมายถึง “ระหว่าง” เมื่อรวมกับ national จึงเป็น international = ระหว่างประเทศ',
    prefix: 'inter-',
    prefixMeaning: 'between / ระหว่าง',
    baseWord: 'national',
    baseMeaning: 'ระดับชาติ',
    newWord: 'international',
    meaning: 'ระหว่างประเทศ',
    sentenceTranslation: 'international หมายถึง เกี่ยวข้องกับหลายประเทศ',
    difficulty: 'medium'
  },
  {
    id: 8,
    planet: 1,
    type: 'matching',
    question: 'Which set matches every prefix with its correct meaning?',
    options: [
      'mono- = one, bi- = two, multi- = many',
      'mono- = many, bi- = one, multi- = two',
      'mono- = two, bi- = many, multi- = one',
      'mono- = half, bi- = after, multi- = before'
    ],
    correctAnswer: 'mono- = one, bi- = two, multi- = many',
    explanation: 'mono- หมายถึงหนึ่ง, bi- หมายถึงสอง และ multi- หมายถึงหลาย',
    prefix: 'mono- / bi- / multi-',
    prefixMeaning: 'one / two / many',
    baseWord: 'lingual',
    baseMeaning: 'เกี่ยวกับภาษา',
    newWord: 'monolingual / bilingual / multilingual',
    meaning: 'ภาษาเดียว / สองภาษา / หลายภาษา',
    sentenceTranslation: 'Prefix กลุ่มจำนวนช่วยบอกจำนวนของภาษา',
    difficulty: 'medium'
  },
  {
    id: 9,
    planet: 1,
    type: 'boss-analysis',
    question: 'BOSS: A sign should mean “not fair.” Which repaired word is correct?',
    options: ['unfair', 'refair', 'prefair', 'interfair'],
    correctAnswer: 'unfair',
    explanation: 'ต้องใช้ un- ซึ่งหมายถึง “ไม่” หน้า fair จึงได้ unfair = ไม่ยุติธรรม',
    prefix: 'un-',
    prefixMeaning: 'not / ไม่',
    baseWord: 'fair',
    baseMeaning: 'ยุติธรรม',
    newWord: 'unfair',
    meaning: 'ไม่ยุติธรรม',
    sentenceTranslation: 'The rule is unfair. = กฎข้อนี้ไม่ยุติธรรม',
    difficulty: 'medium',
    boss: true
  },

  /* =======================================================
     Planet 2: Base Word Forest — Questions 10–18
     ======================================================= */
  {
    id: 10,
    planet: 2,
    type: 'multiple-choice',
    question: 'What is the base word in “disagree”?',
    options: ['agree', 'dis', 'agreement', 'agreeable'],
    correctAnswer: 'agree',
    explanation: 'dis- เป็น Prefix ส่วน agree เป็น Base Word เมื่อนำมารวมกันได้ disagree',
    prefix: 'dis-',
    prefixMeaning: 'not or opposite / ไม่หรือตรงข้าม',
    baseWord: 'agree',
    baseMeaning: 'เห็นด้วย',
    newWord: 'disagree',
    meaning: 'ไม่เห็นด้วย',
    sentenceTranslation: 'I disagree. = ฉันไม่เห็นด้วย',
    difficulty: 'easy'
  },
  {
    id: 11,
    planet: 2,
    type: 'multiple-choice',
    question: 'Which part is the prefix in “misunderstand”?',
    options: ['mis-', 'under-', 'stand', 'understand-'],
    correctAnswer: 'mis-',
    explanation: 'Base Word ทั้งคำคือ understand และเติม mis- ข้างหน้าเพื่อแสดงว่าเข้าใจผิด',
    prefix: 'mis-',
    prefixMeaning: 'wrongly / ผิด',
    baseWord: 'understand',
    baseMeaning: 'เข้าใจ',
    newWord: 'misunderstand',
    meaning: 'เข้าใจผิด',
    sentenceTranslation: 'Do not misunderstand me. = อย่าเข้าใจฉันผิด',
    difficulty: 'easy'
  },
  {
    id: 12,
    planet: 2,
    type: 'multiple-choice',
    question: 'What is the base word in “submarine”?',
    options: ['marine', 'sub', 'mar', 'submarine'],
    correctAnswer: 'marine',
    explanation: 'sub- หมายถึงใต้ ส่วน marine เกี่ยวข้องกับทะเล จึงได้ submarine = เรือดำน้ำ',
    prefix: 'sub-',
    prefixMeaning: 'under / ใต้',
    baseWord: 'marine',
    baseMeaning: 'เกี่ยวกับทะเล',
    newWord: 'submarine',
    meaning: 'เรือดำน้ำ',
    sentenceTranslation: 'The submarine is below the sea. = เรือดำน้ำอยู่ใต้ทะเล',
    difficulty: 'easy'
  },
  {
    id: 13,
    planet: 2,
    type: 'multiple-choice',
    question: 'Which is the correct division of “irregular”?',
    options: ['ir- + regular', 'i- + rregular', 'irre- + gular', 'irreg- + ular'],
    correctAnswer: 'ir- + regular',
    explanation: 'ir- เป็นรูปหนึ่งของ in- ที่ใช้หน้าคำขึ้นต้นด้วย r ส่วน regular เป็น Base Word',
    prefix: 'ir-',
    prefixMeaning: 'not / ไม่',
    baseWord: 'regular',
    baseMeaning: 'สม่ำเสมอหรือเป็นไปตามกฎ',
    newWord: 'irregular',
    meaning: 'ไม่สม่ำเสมอหรือไม่เป็นไปตามกฎ',
    sentenceTranslation: 'irregular verbs = คำกริยาที่ไม่เป็นไปตามกฎ',
    difficulty: 'medium'
  },
  {
    id: 14,
    planet: 2,
    type: 'multiple-choice',
    question: 'Before adding “il-,” what does the base word “legal” mean?',
    options: ['allowed by law', 'against the law', 'done again', 'only partly complete'],
    correctAnswer: 'allowed by law',
    explanation: 'legal หมายถึงถูกกฎหมาย เมื่อเติม il- จึงเป็น illegal = ผิดกฎหมาย',
    prefix: 'il-',
    prefixMeaning: 'not / ไม่',
    baseWord: 'legal',
    baseMeaning: 'ถูกกฎหมาย',
    newWord: 'illegal',
    meaning: 'ผิดกฎหมาย',
    sentenceTranslation: 'legal = ถูกกฎหมาย; illegal = ผิดกฎหมาย',
    difficulty: 'medium'
  },
  {
    id: 15,
    planet: 2,
    type: 'word-assembly',
    question: 'Choose the correct word parts for “to write again.”',
    options: ['re- + write', 'pre- + write', 'mis- + write', 'under- + write'],
    correctAnswer: 're- + write',
    explanation: 're- หมายถึงอีกครั้ง และ write หมายถึงเขียน จึงเป็น rewrite = เขียนใหม่',
    prefix: 're-',
    prefixMeaning: 'again / อีกครั้ง',
    baseWord: 'write',
    baseMeaning: 'เขียน',
    newWord: 'rewrite',
    meaning: 'เขียนใหม่',
    sentenceTranslation: 'Please rewrite your answer. = กรุณาเขียนคำตอบใหม่',
    difficulty: 'easy'
  },
  {
    id: 16,
    planet: 2,
    type: 'word-assembly',
    question: 'Choose the correct parts of “overestimate.”',
    options: ['over- + estimate', 'ov- + erestimate', 'overest- + imate', 'o- + verestimate'],
    correctAnswer: 'over- + estimate',
    explanation: 'over- คือมากเกินไป และ estimate คือประเมิน จึงแยกเป็น over- + estimate',
    prefix: 'over-',
    prefixMeaning: 'too much / มากเกินไป',
    baseWord: 'estimate',
    baseMeaning: 'ประเมิน',
    newWord: 'overestimate',
    meaning: 'ประเมินสูงเกินไป',
    sentenceTranslation: 'We overestimated the cost. = เราประเมินค่าใช้จ่ายสูงเกินไป',
    difficulty: 'medium'
  },
  {
    id: 17,
    planet: 2,
    type: 'word-assembly',
    question: 'Which assembly creates a word meaning “between schools”?',
    options: ['inter- + school', 'in- + terschool', 'pre- + school', 'sub- + school'],
    correctAnswer: 'inter- + school',
    explanation: 'inter- หมายถึงระหว่าง และ school หมายถึงโรงเรียน จึงเป็น interschool = ระหว่างโรงเรียน',
    prefix: 'inter-',
    prefixMeaning: 'between / ระหว่าง',
    baseWord: 'school',
    baseMeaning: 'โรงเรียน',
    newWord: 'interschool',
    meaning: 'ระหว่างโรงเรียน',
    sentenceTranslation: 'an interschool debate = การโต้วาทีระหว่างโรงเรียน',
    difficulty: 'medium'
  },
  {
    id: 18,
    planet: 2,
    type: 'word-assembly',
    question: 'BOSS: Assemble the word that unlocks a door marked “not complete.”',
    options: ['in- + complete = incomplete', 'im- + complete = imcomplete', 'il- + complete = ilcomplete', 'ir- + complete = ircomplete'],
    correctAnswer: 'in- + complete = incomplete',
    explanation: 'complete ขึ้นต้นด้วย c จึงใช้ in- ได้คำว่า incomplete = ไม่สมบูรณ์',
    prefix: 'in-',
    prefixMeaning: 'not / ไม่',
    baseWord: 'complete',
    baseMeaning: 'สมบูรณ์',
    newWord: 'incomplete',
    meaning: 'ไม่สมบูรณ์',
    sentenceTranslation: 'The report is incomplete. = รายงานยังไม่สมบูรณ์',
    difficulty: 'medium',
    boss: true
  },

  /* =======================================================
     Planet 3: Word Factory — Questions 19–27
     ======================================================= */
  {
    id: 19,
    planet: 3,
    type: 'multiple-choice',
    question: 'Which spelling is correct?',
    options: ['impossible', 'inpossible', 'ilpossible', 'irpossible'],
    correctAnswer: 'impossible',
    explanation: 'หน้า Base Word ที่ขึ้นต้นด้วย p ใช้ im- จึงสะกด impossible',
    prefix: 'im-',
    prefixMeaning: 'not / ไม่',
    baseWord: 'possible',
    baseMeaning: 'เป็นไปได้',
    newWord: 'impossible',
    meaning: 'เป็นไปไม่ได้',
    sentenceTranslation: 'It is impossible. = มันเป็นไปไม่ได้',
    difficulty: 'easy'
  },
  {
    id: 20,
    planet: 3,
    type: 'multiple-choice',
    question: 'Which word correctly means “not legal”?',
    options: ['illegal', 'inlegal', 'imlegal', 'irlegal'],
    correctAnswer: 'illegal',
    explanation: 'หน้า Base Word ที่ขึ้นต้นด้วย l ใช้ il- จึงเป็น illegal',
    prefix: 'il-',
    prefixMeaning: 'not / ไม่',
    baseWord: 'legal',
    baseMeaning: 'ถูกกฎหมาย',
    newWord: 'illegal',
    meaning: 'ผิดกฎหมาย',
    sentenceTranslation: 'The action is illegal. = การกระทำนั้นผิดกฎหมาย',
    difficulty: 'easy'
  },
  {
    id: 21,
    planet: 3,
    type: 'multiple-choice',
    question: 'Which word correctly means “not regular”?',
    options: ['irregular', 'inregular', 'imregular', 'ilregular'],
    correctAnswer: 'irregular',
    explanation: 'หน้า Base Word ที่ขึ้นต้นด้วย r ใช้ ir- จึงเป็น irregular',
    prefix: 'ir-',
    prefixMeaning: 'not / ไม่',
    baseWord: 'regular',
    baseMeaning: 'สม่ำเสมอหรือเป็นไปตามกฎ',
    newWord: 'irregular',
    meaning: 'ไม่สม่ำเสมอหรือไม่เป็นไปตามกฎ',
    sentenceTranslation: 'The pattern is irregular. = รูปแบบไม่สม่ำเสมอ',
    difficulty: 'easy'
  },
  {
    id: 22,
    planet: 3,
    type: 'multiple-choice',
    question: 'Which new word means “to connect again”?',
    options: ['reconnect', 'preconnect', 'misconnect', 'underconnect'],
    correctAnswer: 'reconnect',
    explanation: 're- หมายถึงอีกครั้ง จึงใช้ reconnect เมื่อเชื่อมต่อใหม่',
    prefix: 're-',
    prefixMeaning: 'again / อีกครั้ง',
    baseWord: 'connect',
    baseMeaning: 'เชื่อมต่อ',
    newWord: 'reconnect',
    meaning: 'เชื่อมต่อใหม่',
    sentenceTranslation: 'Reconnect the cable. = เชื่อมต่อสายอีกครั้ง',
    difficulty: 'easy'
  },
  {
    id: 23,
    planet: 3,
    type: 'word-assembly',
    question: 'Build the word meaning “to spell wrongly.”',
    options: ['mis- + spell = misspell', 're- + spell = respell', 'pre- + spell = prespell', 'anti- + spell = antispell'],
    correctAnswer: 'mis- + spell = misspell',
    explanation: 'mis- หมายถึงทำอย่างผิด ๆ จึงเป็น misspell = สะกดผิด',
    prefix: 'mis-',
    prefixMeaning: 'wrongly / ผิด',
    baseWord: 'spell',
    baseMeaning: 'สะกด',
    newWord: 'misspell',
    meaning: 'สะกดผิด',
    sentenceTranslation: 'Do not misspell her name. = อย่าสะกดชื่อเธอผิด',
    difficulty: 'easy'
  },
  {
    id: 24,
    planet: 3,
    type: 'word-assembly',
    question: 'Build the adjective meaning “able to use two languages.”',
    options: ['bi- + lingual = bilingual', 'tri- + lingual = trilingual', 'mono- + lingual = monolingual', 'semi- + lingual = semilingual'],
    correctAnswer: 'bi- + lingual = bilingual',
    explanation: 'bi- หมายถึงสอง และ lingual เกี่ยวกับภาษา จึงเป็น bilingual = ใช้ได้สองภาษา',
    prefix: 'bi-',
    prefixMeaning: 'two / สอง',
    baseWord: 'lingual',
    baseMeaning: 'เกี่ยวกับภาษา',
    newWord: 'bilingual',
    meaning: 'ใช้ได้สองภาษา',
    sentenceTranslation: 'She is bilingual. = เธอใช้ได้สองภาษา',
    difficulty: 'medium'
  },
  {
    id: 25,
    planet: 3,
    type: 'word-assembly',
    question: 'Build the word meaning “a person who writes with another author.”',
    options: ['co- + author = coauthor', 'anti- + author = antiauthor', 'sub- + author = subauthor', 'post- + author = postauthor'],
    correctAnswer: 'co- + author = coauthor',
    explanation: 'co- หมายถึงร่วมกัน จึงเป็น coauthor = ผู้เขียนร่วม',
    prefix: 'co-',
    prefixMeaning: 'together / ร่วมกัน',
    baseWord: 'author',
    baseMeaning: 'ผู้เขียน',
    newWord: 'coauthor',
    meaning: 'ผู้เขียนร่วม',
    sentenceTranslation: 'He is my coauthor. = เขาเป็นผู้เขียนร่วมกับฉัน',
    difficulty: 'medium'
  },
  {
    id: 26,
    planet: 3,
    type: 'word-assembly',
    question: 'Build the word meaning “half of a circle.”',
    options: ['semi- + circle = semicircle', 'mono- + circle = monocircle', 'inter- + circle = intercircle', 'post- + circle = postcircle'],
    correctAnswer: 'semi- + circle = semicircle',
    explanation: 'semi- หมายถึงครึ่ง เมื่อรวมกับ circle จึงเป็น semicircle = ครึ่งวงกลม',
    prefix: 'semi-',
    prefixMeaning: 'half / ครึ่ง',
    baseWord: 'circle',
    baseMeaning: 'วงกลม',
    newWord: 'semicircle',
    meaning: 'ครึ่งวงกลม',
    sentenceTranslation: 'Sit in a semicircle. = นั่งเป็นรูปครึ่งวงกลม',
    difficulty: 'medium'
  },
  {
    id: 27,
    planet: 3,
    type: 'boss-analysis',
    question: 'BOSS: The word machine must create “not responsible.” Which output is correct?',
    options: ['irresponsible', 'inresponsible', 'imresponsible', 'ilresponsible'],
    correctAnswer: 'irresponsible',
    explanation: 'responsible ขึ้นต้นด้วย r จึงเปลี่ยน in- เป็น ir- และได้ irresponsible',
    prefix: 'ir-',
    prefixMeaning: 'not / ไม่',
    baseWord: 'responsible',
    baseMeaning: 'มีความรับผิดชอบ',
    newWord: 'irresponsible',
    meaning: 'ไม่มีความรับผิดชอบ',
    sentenceTranslation: 'That behavior is irresponsible. = พฤติกรรมนั้นไม่มีความรับผิดชอบ',
    difficulty: 'hard',
    boss: true
  },

  /* =======================================================
     Planet 4: Sentence City — Questions 28–36
     ======================================================= */
  {
    id: 28,
    planet: 4,
    type: 'multiple-choice',
    question: 'Which word best completes the sentence? “We should _____ glass bottles instead of throwing them away.”',
    options: ['reuse', 'misuse', 'preuse', 'underuse'],
    correctAnswer: 'reuse',
    explanation: 'บริบทบอกให้นำขวดกลับมาใช้ “อีกครั้ง” จึงใช้ reuse',
    prefix: 're-',
    prefixMeaning: 'again / อีกครั้ง',
    baseWord: 'use',
    baseMeaning: 'ใช้',
    newWord: 'reuse',
    meaning: 'นำกลับมาใช้ใหม่',
    sentenceTranslation: 'เราควรนำขวดแก้วกลับมาใช้ใหม่แทนการทิ้ง',
    difficulty: 'easy'
  },
  {
    id: 29,
    planet: 4,
    type: 'multiple-choice',
    question: 'Which word fits? “Do not _____ the pasta, or it will become too soft.”',
    options: ['overcook', 'undercook', 'precook', 'co-cook'],
    correctAnswer: 'overcook',
    explanation: 'too soft บอกว่าปรุงมากเกินไป จึงใช้ overcook',
    prefix: 'over-',
    prefixMeaning: 'too much / มากเกินไป',
    baseWord: 'cook',
    baseMeaning: 'ทำให้สุก',
    newWord: 'overcook',
    meaning: 'ทำให้สุกเกินไป',
    sentenceTranslation: 'อย่าต้มพาสต้านานเกินไป มิฉะนั้นจะนิ่มเกินไป',
    difficulty: 'easy'
  },
  {
    id: 30,
    planet: 4,
    type: 'multiple-choice',
    question: 'Which word fits? “The workers protested because they were _____.”',
    options: ['underpaid', 'overpaid', 'prepaid', 'repaid'],
    correctAnswer: 'underpaid',
    explanation: 'การประท้วงเรื่องค่าจ้างสอดคล้องกับ underpaid = ได้รับค่าจ้างต่ำเกินไป',
    prefix: 'under-',
    prefixMeaning: 'too little / น้อยเกินไป',
    baseWord: 'paid',
    baseMeaning: 'ได้รับค่าจ้าง',
    newWord: 'underpaid',
    meaning: 'ได้รับค่าจ้างต่ำเกินไป',
    sentenceTranslation: 'คนงานประท้วงเพราะได้รับค่าจ้างต่ำเกินไป',
    difficulty: 'medium'
  },
  {
    id: 31,
    planet: 4,
    type: 'sentence-completion',
    question: 'Complete the sentence: “Please _____ the computer after installing the update.”',
    options: ['restart', 'misstart', 'prestart', 'substart'],
    correctAnswer: 'restart',
    explanation: 'หลังติดตั้งอัปเดตต้องเริ่มคอมพิวเตอร์อีกครั้ง จึงใช้ restart',
    prefix: 're-',
    prefixMeaning: 'again / อีกครั้ง',
    baseWord: 'start',
    baseMeaning: 'เริ่ม',
    newWord: 'restart',
    meaning: 'เริ่มใหม่',
    sentenceTranslation: 'กรุณาเริ่มระบบคอมพิวเตอร์ใหม่หลังติดตั้งการอัปเดต',
    difficulty: 'easy'
  },
  {
    id: 32,
    planet: 4,
    type: 'sentence-completion',
    question: 'Complete the sentence: “Because the directions were unclear, we _____ them.”',
    options: ['misunderstood', 'understood', 'previewed', 'cooperated'],
    correctAnswer: 'misunderstood',
    explanation: 'คำแนะนำไม่ชัดทำให้ “เข้าใจผิด” และประโยคเป็นอดีตจึงใช้ misunderstood',
    prefix: 'mis-',
    prefixMeaning: 'wrongly / ผิด',
    baseWord: 'understand',
    baseMeaning: 'เข้าใจ',
    newWord: 'misunderstood',
    meaning: 'เข้าใจผิด (รูปอดีต)',
    sentenceTranslation: 'เพราะคำแนะนำไม่ชัด พวกเราจึงเข้าใจผิด',
    difficulty: 'medium'
  },
  {
    id: 33,
    planet: 4,
    type: 'sentence-completion',
    question: 'Complete the sentence: “It is _____ to copy another person’s passport.”',
    options: ['illegal', 'irregular', 'inactive', 'impossible'],
    correctAnswer: 'illegal',
    explanation: 'การคัดลอกหนังสือเดินทางผู้อื่นเป็นสิ่งผิดกฎหมาย จึงใช้ illegal',
    prefix: 'il-',
    prefixMeaning: 'not / ไม่',
    baseWord: 'legal',
    baseMeaning: 'ถูกกฎหมาย',
    newWord: 'illegal',
    meaning: 'ผิดกฎหมาย',
    sentenceTranslation: 'การคัดลอกหนังสือเดินทางของบุคคลอื่นเป็นสิ่งผิดกฎหมาย',
    difficulty: 'medium'
  },
  {
    id: 34,
    planet: 4,
    type: 'sentence-completion',
    question: 'Complete the sentence: “Our school hosted an _____ science fair with teams from four countries.”',
    options: ['international', 'underground', 'postgraduate', 'semifinal'],
    correctAnswer: 'international',
    explanation: 'มีทีมจากสี่ประเทศจึงเป็นงานระดับนานาชาติ หรือ international',
    prefix: 'inter-',
    prefixMeaning: 'between / ระหว่าง',
    baseWord: 'national',
    baseMeaning: 'ระดับชาติ',
    newWord: 'international',
    meaning: 'ระหว่างประเทศ',
    sentenceTranslation: 'โรงเรียนจัดงานวิทยาศาสตร์นานาชาติที่มีทีมจากสี่ประเทศ',
    difficulty: 'medium'
  },
  {
    id: 35,
    planet: 4,
    type: 'sentence-completion',
    question: 'Complete the sentence: “The two groups must _____ to finish the project on time.”',
    options: ['cooperate', 'disconnect', 'overestimate', 'misbehave'],
    correctAnswer: 'cooperate',
    explanation: 'สองกลุ่มต้อง “ร่วมมือกัน” จึงใช้ cooperate ซึ่งมี co- หมายถึงร่วมกัน',
    prefix: 'co-',
    prefixMeaning: 'together / ร่วมกัน',
    baseWord: 'operate',
    baseMeaning: 'ดำเนินการ',
    newWord: 'cooperate',
    meaning: 'ร่วมมือกัน',
    sentenceTranslation: 'ทั้งสองกลุ่มต้องร่วมมือกันเพื่อทำโครงการให้เสร็จตรงเวลา',
    difficulty: 'medium'
  },
  {
    id: 36,
    planet: 4,
    type: 'matching',
    question: 'BOSS: Which word-to-situation matching set will restore the city communication system?',
    options: [
      'disconnect = stop a connection; reconnect = connect again',
      'disconnect = connect again; reconnect = stop a connection',
      'disconnect = connect before; reconnect = connect too much',
      'disconnect = connect below; reconnect = connect wrongly'
    ],
    correctAnswer: 'disconnect = stop a connection; reconnect = connect again',
    explanation: 'dis- ใน disconnect แสดงการแยกหรือตัดออก ส่วน re- ใน reconnect แสดงการเชื่อมต่ออีกครั้ง',
    prefix: 'dis- / re-',
    prefixMeaning: 'apart / again',
    baseWord: 'connect',
    baseMeaning: 'เชื่อมต่อ',
    newWord: 'disconnect / reconnect',
    meaning: 'ตัดการเชื่อมต่อ / เชื่อมต่อใหม่',
    sentenceTranslation: 'Disconnect the old cable, then reconnect it. = ถอดสายเก่าแล้วเชื่อมต่อใหม่',
    difficulty: 'hard',
    boss: true
  },

  /* =======================================================
     Planet 5: Master Galaxy — Questions 37–45
     ======================================================= */
  {
    id: 37,
    planet: 5,
    type: 'multiple-choice',
    question: 'A student previews a chapter and later reviews it. What is the correct difference?',
    options: [
      'preview = look before; review = look again',
      'preview = look again; review = look before',
      'both words mean look wrongly',
      'both words mean look below'
    ],
    correctAnswer: 'preview = look before; review = look again',
    explanation: 'pre- หมายถึงก่อน จึง preview ก่อนอ่าน ส่วน re- หมายถึงอีกครั้ง จึง review หลังเรียน',
    prefix: 'pre- / re-',
    prefixMeaning: 'before / again',
    baseWord: 'view',
    baseMeaning: 'ดู',
    newWord: 'preview / review',
    meaning: 'ดูล่วงหน้า / ทบทวนหรือดูอีกครั้ง',
    sentenceTranslation: 'นักเรียนดูล่วงหน้าก่อนเรียนและทบทวนอีกครั้งหลังเรียน',
    difficulty: 'hard'
  },
  {
    id: 38,
    planet: 5,
    type: 'multiple-choice',
    question: 'Without using a dictionary, what most likely is a “semicircular table”?',
    options: ['a table shaped like half a circle', 'a table with three corners', 'a table below the floor', 'a table used after a final'],
    correctAnswer: 'a table shaped like half a circle',
    explanation: 'semi- หมายถึงครึ่ง และ circular เกี่ยวกับวงกลม จึงหมายถึงโต๊ะรูปครึ่งวงกลม',
    prefix: 'semi-',
    prefixMeaning: 'half / ครึ่ง',
    baseWord: 'circular',
    baseMeaning: 'เป็นวงกลม',
    newWord: 'semicircular',
    meaning: 'เป็นรูปครึ่งวงกลม',
    sentenceTranslation: 'a semicircular table = โต๊ะรูปครึ่งวงกลม',
    difficulty: 'hard'
  },
  {
    id: 39,
    planet: 5,
    type: 'multiple-choice',
    question: 'A “transcontinental railway” most likely travels where?',
    options: ['across a continent', 'under a school', 'between two rooms only', 'around half a circle'],
    correctAnswer: 'across a continent',
    explanation: 'trans- หมายถึงข้าม และ continental เกี่ยวกับทวีป จึงเป็นทางรถไฟที่เดินทางข้ามทวีป',
    prefix: 'trans-',
    prefixMeaning: 'across / ข้าม',
    baseWord: 'continental',
    baseMeaning: 'เกี่ยวกับทวีป',
    newWord: 'transcontinental',
    meaning: 'ข้ามทวีป',
    sentenceTranslation: 'a transcontinental railway = ทางรถไฟข้ามทวีป',
    difficulty: 'hard'
  },
  {
    id: 40,
    planet: 5,
    type: 'multiple-choice',
    question: 'If two systems are “interdependent,” what can you infer?',
    options: ['They depend on each other.', 'They never work together.', 'One works only before the other.', 'Both are below standard.'],
    correctAnswer: 'They depend on each other.',
    explanation: 'inter- หมายถึงระหว่างกัน และ dependent หมายถึงพึ่งพา จึงแปลว่าต่างฝ่ายต่างพึ่งพากัน',
    prefix: 'inter-',
    prefixMeaning: 'between or among / ระหว่างกัน',
    baseWord: 'dependent',
    baseMeaning: 'ต้องพึ่งพา',
    newWord: 'interdependent',
    meaning: 'พึ่งพาซึ่งกันและกัน',
    sentenceTranslation: 'สองระบบพึ่งพาซึ่งกันและกัน',
    difficulty: 'hard'
  },
  {
    id: 41,
    planet: 5,
    type: 'multiple-choice',
    question: 'In “Do not underestimate the time needed,” what warning is being given?',
    options: ['Do not judge the time as less than it really is.', 'Do not repeat the time.', 'Do not measure time before starting.', 'Do not divide the time into two parts.'],
    correctAnswer: 'Do not judge the time as less than it really is.',
    explanation: 'under- แสดงว่าน้อยเกินไป และ estimate คือประเมิน จึงเตือนว่าอย่าประเมินเวลาต่ำกว่าความจริง',
    prefix: 'under-',
    prefixMeaning: 'too little / น้อยเกินไป',
    baseWord: 'estimate',
    baseMeaning: 'ประเมิน',
    newWord: 'underestimate',
    meaning: 'ประเมินต่ำเกินไป',
    sentenceTranslation: 'อย่าประเมินเวลาที่ต้องใช้ต่ำกว่าความเป็นจริง',
    difficulty: 'hard'
  },
  {
    id: 42,
    planet: 5,
    type: 'multiple-choice',
    question: 'Which word best describes a school community with students from many cultures?',
    options: ['multicultural', 'monocultural', 'semicultural', 'postcultural'],
    correctAnswer: 'multicultural',
    explanation: 'multi- หมายถึงหลาย จึงใช้ multicultural เมื่อมีหลายวัฒนธรรมอยู่ร่วมกัน',
    prefix: 'multi-',
    prefixMeaning: 'many / หลาย',
    baseWord: 'cultural',
    baseMeaning: 'เกี่ยวกับวัฒนธรรม',
    newWord: 'multicultural',
    meaning: 'หลากหลายวัฒนธรรม',
    sentenceTranslation: 'ชุมชนโรงเรียนที่มีนักเรียนจากหลายวัฒนธรรมเป็นชุมชนพหุวัฒนธรรม',
    difficulty: 'medium'
  },
  {
    id: 43,
    planet: 5,
    type: 'matching',
    question: 'Which set correctly matches the words with their meanings?',
    options: [
      'overestimate = judge too high; underestimate = judge too low',
      'overestimate = judge too low; underestimate = judge too high',
      'overestimate = judge again; underestimate = judge before',
      'overestimate = judge together; underestimate = judge against'
    ],
    correctAnswer: 'overestimate = judge too high; underestimate = judge too low',
    explanation: 'over- แสดงว่ามากเกินไป ส่วน under- แสดงว่าน้อยเกินไป จึงให้ความหมายตรงข้ามกัน',
    prefix: 'over- / under-',
    prefixMeaning: 'too much / too little',
    baseWord: 'estimate',
    baseMeaning: 'ประเมิน',
    newWord: 'overestimate / underestimate',
    meaning: 'ประเมินสูงเกินไป / ประเมินต่ำเกินไป',
    sentenceTranslation: 'คำทั้งสองใช้ Base Word เดียวกัน แต่ Prefix ทำให้ความหมายตรงข้ามกัน',
    difficulty: 'hard'
  },
  {
    id: 44,
    planet: 5,
    type: 'matching',
    question: 'Which set correctly matches each context with the best word?',
    options: [
      'before the game = pregame; after the game = postgame; play again = replay',
      'before the game = postgame; after the game = pregame; play again = misplay',
      'before the game = replay; after the game = pregame; play again = postgame',
      'before the game = undergame; after the game = intergame; play again = antigame'
    ],
    correctAnswer: 'before the game = pregame; after the game = postgame; play again = replay',
    explanation: 'pre- = ก่อน, post- = หลัง และ re- = อีกครั้ง จึงจับคู่ได้ตามลำดับนี้',
    prefix: 'pre- / post- / re-',
    prefixMeaning: 'before / after / again',
    baseWord: 'game / play',
    baseMeaning: 'เกม / เล่น',
    newWord: 'pregame / postgame / replay',
    meaning: 'ก่อนเกม / หลังเกม / เล่นซ้ำ',
    sentenceTranslation: 'Prefix บอกลำดับเวลาและการทำซ้ำได้',
    difficulty: 'hard'
  },
  {
    id: 45,
    planet: 5,
    type: 'boss-analysis',
    question: 'FINAL BOSS: A team receives this message: “The plan is impractical because it underestimates the cost.” Which analysis is correct?',
    options: [
      'im- + practical = not practical; under- + estimate = estimate too low',
      'im- + practical = practical again; under- + estimate = estimate too high',
      'im- + practical = before practical; under- + estimate = estimate together',
      'im- + practical = partly practical; under- + estimate = estimate after'
    ],
    correctAnswer: 'im- + practical = not practical; under- + estimate = estimate too low',
    explanation: 'im- เป็นรูปของ in- ที่หมายถึง “ไม่” หน้า practical ส่วน under- หมายถึงน้อยเกินไป หน้า estimate ดังนั้นแผนใช้ไม่ได้จริงเพราะประเมินต้นทุนต่ำเกินไป',
    prefix: 'im- / under-',
    prefixMeaning: 'not / too little',
    baseWord: 'practical / estimate',
    baseMeaning: 'ใช้ได้จริง / ประเมิน',
    newWord: 'impractical / underestimate',
    meaning: 'ใช้ไม่ได้จริง / ประเมินต่ำเกินไป',
    sentenceTranslation: 'แผนนี้ใช้ไม่ได้จริง เพราะประเมินค่าใช้จ่ายต่ำเกินไป',
    difficulty: 'hard',
    boss: true
  }
];
